# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RoletaRussa_' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RoletaRussa_
	pod 'SCLAlertView', '~> 0.8'
end
